# This is a basic workflow to help you get started with Actions

name: CI-OSX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v2

      - name: run makeshit
        run: |
          npm install
          npm run make all

          mkdir -p /tmp/builds


          cd /Users/runner/work/quest-sidenoder/quest-sidenoder/out/make
          mkdir -p /tmp/builds/darwin/dmg/
          mv *.dmg /tmp/builds/darwin/dmg/
          cd /Users/runner/work/quest-sidenoder/quest-sidenoder/out/make/zip/darwin/x64/
          mkdir -p /tmp/builds/darwin/zip/
          sudo mv *.zip /tmp/builds/darwin/zip/


      - name: Upload darwin Build dmg Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sidenoder-darwin-x64-dmg
          path: /tmp/builds/darwin/dmg/
      - name: Upload darwin Build zip Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sidenoder-darwin-x64-zip
          path: /tmp/builds/darwin/zip/