# This is a basic workflow to help you get started with Actions

name: CI-WINDOWS-OTHER

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2



      - name: electron-packager
        run: |

          npm install
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install wine32
          sudo apt install wine64
          sudo npm install electron-packager -g
          sudo electron-packager ./ sidenoder --platform=win32 --arch=x64 --icon=build/icon.png

          sudo cp /home/runner/work/quest-sidenoder/quest-sidenoder/windows-install.bat /home/runner/work/quest-sidenoder/quest-sidenoder/sidenoder-win32-x64/windows-install.bat
          cd /home/runner/work/quest-sidenoder/quest-sidenoder/sidenoder-win32-x64/
          mkdir -p /tmp/builds/win32/x64/
          zip -r /tmp/builds/win32/x64/sidenoder-win32-x64.zip *


      - name: Upload windows Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sidenoder-win32-x64
          path: /tmp/builds/win32/x64/sidenoder-win32-x64.zip